chat:
  public: "%prefix% <gray>⋆</gray> %player% <gray>» <white>%message%"
  private: "<gray>[<red>MSG</red>]</gray> <white>%sender% <dark_gray>» <white>%receiver% <gray>» <white>%message%"

back-cost: 100

item-signature:
  - "&e"
  - "<gray>⋆</gray> <white>%player%"
  - "<gray>⋆</gray> <white>%message%"
  - "&f"