chat:
  public: "%prefix% <gray>⋆</gray> %player% <gray>» <white>%message%"
  private: "<gray>[<red>MSG</red>]</gray> <white>%sender% <dark_gray>» <white>%receiver% <gray>» <white>%message%"

back-cost: 100