name: AkaniEssentials
main: it.einjojo.akani.essentials.AkaniEssentialsPlugin
version: ${version}
api-version: "1.19"
author: "EinJOJO @ Kalypzo.de"
website: https://kalypzo.de
description: AkaniCore has been created to provide a core for all Akani plugins.
depend: [ AkaniCore, PlaceholderAPI ]
libraries:
  - "com.github.ben-manes.caffeine:caffeine:3.1.8"